/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: src/sanity/extract.json
export type SkillCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'skillCategory';
};

export type Skill = {
  _id: string;
  _type: 'skill';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: InternationalizedArrayString;
  category?: SkillCategoryReference;
  accentColor?: 'teal' | 'lavender' | 'pink' | 'peach' | 'green' | 'sky';
  tags?: Array<string>;
  proficiency?: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  svgCode?: string;
};

export type SkillCategory = {
  _id: string;
  _type: 'skillCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: InternationalizedArrayString;
  slug?: Slug;
  accentColor?: 'teal' | 'lavender' | 'pink' | 'peach' | 'green' | 'sky';
  order?: number;
  fallbackSvgCode?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type SkillReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'skill';
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: InternationalizedArrayString;
  description?: InternationalizedArrayString;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  url?: string;
  repo?: string;
  date?: string;
  skills?: Array<
    {
      _key: string;
    } & SkillReference
  >;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Experience = {
  _id: string;
  _type: 'experience';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  company?: string;
  location?: string;
  startDate?: string;
  endDate?: string;
  description?: InternationalizedArrayString;
  skills?: Array<
    {
      _key: string;
    } & SkillReference
  >;
};

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue';
  value?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SkillCategoryReference
  | Skill
  | SkillCategory
  | Slug
  | InternationalizedArrayString
  | SanityImageAssetReference
  | SkillReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Experience
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: src/sanity/queries.ts
// Variable: listProjectsQuery
// Query: *[_type == "project"] {     ...,    skills[]->  } | order(date desc)
export type ListProjectsQueryResult = Array<{
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: InternationalizedArrayString;
  description?: InternationalizedArrayString;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  url?: string;
  repo?: string;
  date?: string;
  skills: Array<{
    _id: string;
    _type: 'skill';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    description?: InternationalizedArrayString;
    category?: SkillCategoryReference;
    accentColor?: 'green' | 'lavender' | 'peach' | 'pink' | 'sky' | 'teal';
    tags?: Array<string>;
    proficiency?: 'advanced' | 'beginner' | 'expert' | 'intermediate';
    svgCode?: string;
  }> | null;
}>;

// Source: src/sanity/queries.ts
// Variable: previewProjectsQuery
// Query: *[_type == "project"] {     ...,    skills[]->  } | order(date desc)[0..1]
export type PreviewProjectsQueryResult = Array<{
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: InternationalizedArrayString;
  description?: InternationalizedArrayString;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  url?: string;
  repo?: string;
  date?: string;
  skills: Array<{
    _id: string;
    _type: 'skill';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    description?: InternationalizedArrayString;
    category?: SkillCategoryReference;
    accentColor?: 'green' | 'lavender' | 'peach' | 'pink' | 'sky' | 'teal';
    tags?: Array<string>;
    proficiency?: 'advanced' | 'beginner' | 'expert' | 'intermediate';
    svgCode?: string;
  }> | null;
}>;

// Source: src/sanity/queries.ts
// Variable: listExperiencesQuery
// Query: *[_type == "experience"] | order(endDate desc)
export type ListExperiencesQueryResult = Array<{
  _id: string;
  _type: 'experience';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  company?: string;
  location?: string;
  startDate?: string;
  endDate?: string;
  description?: InternationalizedArrayString;
  skills?: Array<
    {
      _key: string;
    } & SkillReference
  >;
}>;

// Source: src/sanity/queries.ts
// Variable: previewExperiencesQuery
// Query: *[_type == "experience"] | order(endDate desc)[0..2]
export type PreviewExperiencesQueryResult = Array<{
  _id: string;
  _type: 'experience';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  company?: string;
  location?: string;
  startDate?: string;
  endDate?: string;
  description?: InternationalizedArrayString;
  skills?: Array<
    {
      _key: string;
    } & SkillReference
  >;
}>;

// Source: src/sanity/queries.ts
// Variable: listSkillsQuery
// Query: *[ _type == "skill"] {    ...,    category->  } | order(category->order asc, name asc)
export type ListSkillsQueryResult = Array<{
  _id: string;
  _type: 'skill';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: InternationalizedArrayString;
  category: {
    _id: string;
    _type: 'skillCategory';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: InternationalizedArrayString;
    slug?: Slug;
    accentColor?: 'green' | 'lavender' | 'peach' | 'pink' | 'sky' | 'teal';
    order?: number;
    fallbackSvgCode?: string;
  } | null;
  accentColor?: 'green' | 'lavender' | 'peach' | 'pink' | 'sky' | 'teal';
  tags?: Array<string>;
  proficiency?: 'advanced' | 'beginner' | 'expert' | 'intermediate';
  svgCode?: string;
}>;

// Source: src/sanity/queries.ts
// Variable: previewSkillsQuery
// Query: *[ _type == "skill"] {    ...,    category->  } | order(category->order asc, name asc)[0..4]
export type PreviewSkillsQueryResult = Array<{
  _id: string;
  _type: 'skill';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: InternationalizedArrayString;
  category: {
    _id: string;
    _type: 'skillCategory';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: InternationalizedArrayString;
    slug?: Slug;
    accentColor?: 'green' | 'lavender' | 'peach' | 'pink' | 'sky' | 'teal';
    order?: number;
    fallbackSvgCode?: string;
  } | null;
  accentColor?: 'green' | 'lavender' | 'peach' | 'pink' | 'sky' | 'teal';
  tags?: Array<string>;
  proficiency?: 'advanced' | 'beginner' | 'expert' | 'intermediate';
  svgCode?: string;
}>;

// Source: src/sanity/queries.ts
// Variable: listSkillCategoriesQuery
// Query: *[ _type == "skillCategory"] | order(order asc)
export type ListSkillCategoriesQueryResult = Array<{
  _id: string;
  _type: 'skillCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: InternationalizedArrayString;
  slug?: Slug;
  accentColor?: 'green' | 'lavender' | 'peach' | 'pink' | 'sky' | 'teal';
  order?: number;
  fallbackSvgCode?: string;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "project"] { \n    ...,\n    skills[]->\n  } | order(date desc)\n': ListProjectsQueryResult;
    '\n  *[_type == "project"] { \n    ...,\n    skills[]->\n  } | order(date desc)[0..1]\n': PreviewProjectsQueryResult;
    '\n  *[_type == "experience"] | order(endDate desc)\n': ListExperiencesQueryResult;
    '\n  *[_type == "experience"] | order(endDate desc)[0..2]\n': PreviewExperiencesQueryResult;
    '\n  *[ _type == "skill"] {\n    ...,\n    category->\n  } | order(category->order asc, name asc)\n': ListSkillsQueryResult;
    '\n  *[ _type == "skill"] {\n    ...,\n    category->\n  } | order(category->order asc, name asc)[0..4]\n': PreviewSkillsQueryResult;
    '\n  *[ _type == "skillCategory"] | order(order asc)\n': ListSkillCategoriesQueryResult;
  }
}
