import { type NextPage } from 'next'
import Head from 'next/head'

import { useState, useEffect, useRef } from 'react'
import { useCtpStore, type Flavor } from '~/store'
import Header from '~/components/Header'
import BackgroundBlurSVG from '~/components/BackgroundBlurSVG'
import ProgrammingSVG from '~/components/ProgrammingSVG'
import Typed from 'typed.js'

const Home: NextPage = () => {
  const activeFlavor = useCtpStore((state) => state.flavor)
  const [flavor, setFlavor] = useState<Flavor>('mocha')

  const phraseRef = useRef(null)
  const nameRef = useRef(null)

  useEffect(() => {
    // const phrase = new Typed(phraseRef.current, {
    //   strings: [
    //     'Ambition without effort is merely greed',
    //     'Make money and stay alive'
    //   ],
    //   typeSpeed: 50,
    //   backSpeed: 50,
    //   loop: true
    // })

    const name = new Typed(nameRef.current, {
      strings: ['Anderson Ribeiro Lopes'],
      typeSpeed: 50
    })

    return () => {
      // Destroy Typed instance during cleanup to stop animation
      // phrase.destroy()
      name.destroy()
    }
  }, [])

  useEffect(() => {
    setFlavor(activeFlavor)
  }, [activeFlavor])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`ctp-${flavor} min-w-screen min-h-screen bg-ctp-base`}>
        <Header />
        <div className="relative isolate min-h-screen px-6 pt-14 lg:px-8">
          <div className="min-w-screen flex min-h-[80vh] flex-col justify-between p-2 md:flex-row md:p-12">
            <div className="animate-colorchange bg-gradient-to-r from-ctp-teal via-ctp-lavender bg-clip-text py-2 pt-12 text-transparent">
              <span
                className="text-left text-6xl font-bold tracking-tight"
                ref={nameRef}
              ></span>
              <p className="text-left text-lg font-semibold">
                Desenvolvedor Full Stack
              </p>
            </div>
            <div className="flex">
              <ProgrammingSVG />
            </div>
          </div>
        </div>
        <BackgroundBlurSVG />
      </main>
    </>
  )
}

export default Home


