import { type NextPage } from 'next'
import Head from 'next/head'
import { signIn, signOut, useSession } from 'next-auth/react'
import ProjectList from '~/components/projects/ProjectList'
import { useState, useEffect } from 'react'
import { useCtpStore, Flavor, flavors } from '../store'
import Header from '~/components/Header'
import HeroSection from '~/components/HeroSection'
import { type variants } from '@catppuccin/palette'

const Home: NextPage = () => {
  const activeFlavor = useCtpStore((state) => state.flavor)
  const [flavor, setFlavor] = useState(Flavor.latte)

  useEffect(() => {
    setFlavor(activeFlavor)
  }, [activeFlavor])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${flavor} min-w-screen min-h-screen bg-ctp-base`}>
        <Header />
        <HeroSection
          flavorLabel={flavors[flavor].toLowerCase() as keyof typeof variants}
        />
        <ProjectList />
      </main>
    </>
  )
}

export default Home

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession()

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? 'Sign out' : 'Sign in'}
      </button>
    </div>
  )
}
